// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvA7t39pzEik1yqbn5_X1PnTrb55VzxK4',
    appId: '1:651137733892:web:cdb64ef1f4e3faa388ec51',
    messagingSenderId: '651137733892',
    projectId: 'mobilebob-b7094',
    authDomain: 'mobilebob-b7094.firebaseapp.com',
    storageBucket: 'mobilebob-b7094.appspot.com',
    measurementId: 'G-CEEYGEWC8T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD57UB2eJ9RY5vzBvz-GxCURMHskLWNp_U',
    appId: '1:651137733892:android:9589e02a49543e4b88ec51',
    messagingSenderId: '651137733892',
    projectId: 'mobilebob-b7094',
    storageBucket: 'mobilebob-b7094.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALzTvIVDXXV7vtLmLbbu4RN-qEe3Y8NPg',
    appId: '1:651137733892:ios:3b3dea8b62752c2188ec51',
    messagingSenderId: '651137733892',
    projectId: 'mobilebob-b7094',
    storageBucket: 'mobilebob-b7094.appspot.com',
    iosBundleId: 'com.example.fireflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALzTvIVDXXV7vtLmLbbu4RN-qEe3Y8NPg',
    appId: '1:651137733892:ios:145b17b8eacdac7588ec51',
    messagingSenderId: '651137733892',
    projectId: 'mobilebob-b7094',
    storageBucket: 'mobilebob-b7094.appspot.com',
    iosBundleId: 'com.example.fireflutter.RunnerTests',
  );
}
